/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convolucion;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DELL
 */
public class FormConvolucion extends javax.swing.JFrame {
    
    private static int[][]BLUR = {{0,0,1,0,0},
			      {0,1,1,1,0},
			      {1,1,1,1,1},
			      {0,1,1,1,0},
                              {0,0,1,0,0}
    };
    
    private static int[][]MONTIONBLUR = {{1,0,0,0,0},
				    {0,1,0,0,0},
				    {0,0,1,0,0},
				    {0,0,0,1,0},
				    {0,0,0,0,1}
    };
    
    private static int[][]EDGES = {{-1,-1,-1,-1,-1},
                               {-1,-1,-1,-1,-1},
                               {-1,-1,24,-1,-1},
                               {-1,-1,-1,-1,-1},
                               {-1,-1,-1,-1,-1}
    };
    
    private static int[][]SHARPEN = {{-1,-1,-1,-1,-1},
                                 {-1,-1,-1,-1,-1},
                                 {-1,-1,25,-1,-1},
                                 {-1,-1,-1,-1,-1},
                                 {-1,-1,-1,-1,-1}
    };
    
    private static int[][]EMBOSS = {{-1,-1,-1,-1, 0},
                                 {-1,-1,-1, 0, 1},
                                 {-1,-1, 0, 1, 1},
                                 {-1, 0, 1, 1, 1},
                                 { 0, 1, 1, 1, 1}
    };
    
    private static int[][] NORMAL = {
        {-1, -1, -1},
        {0, 0, 0},
        {1, 1, 1}
    };

    private BufferedImage imagen;
    private File seleccion;
    /**
     * Creates new form FormConvolucion
     */
    public FormConvolucion() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonGroup1.add(radioBlur);
        buttonGroup1.add(radioEdge);
        buttonGroup1.add(radioEmboss);
        buttonGroup1.add(radioNormal);
        buttonGroup1.add(radioSharpen);
        buttonGroup1.add(radiob);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnImportar = new javax.swing.JButton();
        radioBlur = new javax.swing.JRadioButton();
        radioEdge = new javax.swing.JRadioButton();
        radioSharpen = new javax.swing.JRadioButton();
        radioNormal = new javax.swing.JRadioButton();
        radioEmboss = new javax.swing.JRadioButton();
        txt6 = new javax.swing.JLabel();
        txt7 = new javax.swing.JLabel();
        txt8 = new javax.swing.JLabel();
        btnAplicar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        btnOriginal = new javax.swing.JButton();
        radiob = new javax.swing.JRadioButton();
        txt9 = new javax.swing.JLabel();
        txt10 = new javax.swing.JLabel();
        txt11 = new javax.swing.JLabel();
        txt12 = new javax.swing.JLabel();
        txt13 = new javax.swing.JLabel();
        txt14 = new javax.swing.JLabel();
        txt15 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        txt16 = new javax.swing.JLabel();
        txt17 = new javax.swing.JLabel();
        txt18 = new javax.swing.JLabel();
        txt19 = new javax.swing.JLabel();
        txt20 = new javax.swing.JLabel();
        txt21 = new javax.swing.JLabel();
        txt22 = new javax.swing.JLabel();
        txt23 = new javax.swing.JLabel();
        txt24 = new javax.swing.JLabel();
        txt25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Convolución Imagen");

        btnImportar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnImportar.setText("Importar Imagen");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        radioBlur.setText("MontionBlur");
        radioBlur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBlurActionPerformed(evt);
            }
        });

        radioEdge.setText("Edges");
        radioEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEdgeActionPerformed(evt);
            }
        });

        radioSharpen.setText("Sharpen");
        radioSharpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSharpenActionPerformed(evt);
            }
        });

        radioNormal.setText("Normal 3x3");
        radioNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNormalActionPerformed(evt);
            }
        });

        radioEmboss.setText("Emboss");
        radioEmboss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEmbossActionPerformed(evt);
            }
        });

        txt6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt6.setText("0");

        txt7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt7.setText("0");

        txt8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt8.setText("0");

        btnAplicar.setText("Aplicar Filtro");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        lblImagen.setToolTipText("");

        btnOriginal.setText("Original");
        btnOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOriginalActionPerformed(evt);
            }
        });

        radiob.setText("Blur");
        radiob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobActionPerformed(evt);
            }
        });

        txt9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt9.setText("0");

        txt10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt10.setText("0");

        txt11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt11.setText("0");

        txt12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt12.setText("0");

        txt13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt13.setText("0");

        txt14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt14.setText("0");

        txt15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt15.setText("0");

        txt1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("0");

        txt2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt2.setText("0");

        txt3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt3.setText("0");

        txt4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt4.setText("0");

        txt5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt5.setText("0");

        txt16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt16.setText("0");

        txt17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt17.setText("0");

        txt18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt18.setText("0");

        txt19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt19.setText("0");

        txt20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt20.setText("0");

        txt21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt21.setText("0");

        txt22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt22.setText("0");

        txt23.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt23.setText("0");

        txt24.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt24.setText("0");

        txt25.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt25.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioEdge)
                            .addComponent(radioBlur)
                            .addComponent(radioEmboss))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioSharpen)
                            .addComponent(radiob)
                            .addComponent(radioNormal))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(txt18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAplicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOriginal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txt23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSharpen)
                    .addComponent(radioEmboss)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBlur)
                    .addComponent(radioNormal)
                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioEdge)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiob)
                            .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEdgeActionPerformed
        setLabelsNum(EDGES);
    }//GEN-LAST:event_radioEdgeActionPerformed

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        File imagenSeleccionada;
        JFileChooser selector = new JFileChooser();
        selector.setDialogTitle("Seleccione una imagen");
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("JPG & GIF & BMP", "jpg", "gif", "bmp");
        selector.setFileFilter(filtroImagen);
        int flag = selector.showOpenDialog(this);
        if (flag == JFileChooser.APPROVE_OPTION) {
            try {
                imagenSeleccionada = selector.getSelectedFile();
                seleccion = imagenSeleccionada;
                this.imagen = ImageIO.read(imagenSeleccionada);
                setImagenPanel();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnImportarActionPerformed

    private void aplicar(int[][] m, double multi, double extra) { //matriz 3x3
        if (imagen != null) {
            BufferedImage nuevo = imagen;
            for (int i = 0; i < imagen.getWidth(); i++) {
                for (int j = 0; j < imagen.getHeight(); j++) {
                    //int rgb = imagen.getRGB(i, j);
                    int r = 0, g = 0, b = 0;
                    int k = 0;
                    for (int n = i - 1; n <= i + 1; n++) {
                        int l=0;
                        for (int o = j - 1; o <= j + 1; o++) {
                            if (n >= 0 && o >= 0 && n < imagen.getWidth() && o < imagen.getHeight()) {
                                int t = imagen.getRGB(n, o);
                                Color e = new Color(t);
                                r = r + (e.getRed() * m[k][l]);
                                g = g + (e.getGreen() * m[k][l]);
                                b = b + (e.getBlue() * m[k][l]);
                            }
                            l++;
                        }
                        k++;
                    }
                    int red = (int) (r*multi+extra);
                    int green = (int) (g*multi+extra);
                    int blue = (int) (b*multi+extra);
                    Color color = new Color(verificar(red), verificar(green), verificar(blue));
                    nuevo.setRGB(i, j, color.getRGB());
                }
            }
            this.lblImagen.setIcon(new ImageIcon(nuevo));
        }
    }
    
    private void aplicar2(int[][] m, double multi, double extra) { //matriz5x5
        if (imagen != null) {
            BufferedImage nuevo = imagen;
            for (int i = 0; i < imagen.getWidth(); i++) {
                for (int j = 0; j < imagen.getHeight(); j++) {
                    //int rgb = imagen.getRGB(i, j);
                    int r = 0, g = 0, b = 0;
                    int k = 0;
                    for (int n = i - 2; n <= i + 2; n++) {
                        int l=0;
                        for (int o = j - 2; o <= j + 2; o++) {
                            if (n >= 0 && o >= 0 && n < imagen.getWidth() && o < imagen.getHeight()) {
                                int t = imagen.getRGB(n, o);
                                Color e = new Color(t);
                                r = r + (e.getRed() * m[k][l]);
                                g = g + (e.getGreen() * m[k][l]);
                                b = b + (e.getBlue() * m[k][l]);
                            }
                            l++;
                        }
                        k++;
                    }
                    int red = (int) (r*multi+extra);
                    int green = (int) (g*multi+extra);
                    int blue = (int) (b*multi+extra);
                    Color color = new Color(verificar(red), verificar(green), verificar(blue));
                    nuevo.setRGB(i, j, color.getRGB());
                }
            }
            this.lblImagen.setIcon(new ImageIcon(nuevo));
        }
    }
    

    private Integer verificar(int x) {
        //int f = Math.abs(x);
        if (x <= 255 && x>=0) {
            return x;
        } else if(x<0){
            return 0;
        }else{
            return 255;
        }
    }

    private void btnOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOriginalActionPerformed
        setImagenPanel();
    }//GEN-LAST:event_btnOriginalActionPerformed

    private void radioEmbossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEmbossActionPerformed
        setLabelsNum(EMBOSS);
    }//GEN-LAST:event_radioEmbossActionPerformed

    private void radioSharpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSharpenActionPerformed
        setLabelsNum(SHARPEN);
    }//GEN-LAST:event_radioSharpenActionPerformed

    private void radioBlurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBlurActionPerformed
        setLabelsNum(MONTIONBLUR);
    }//GEN-LAST:event_radioBlurActionPerformed

    private void radioNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNormalActionPerformed
       txt1.setText("-");
        txt2.setText("-");
        txt3.setText("-");
        txt4.setText("-");
        txt5.setText("-");
        txt6.setText("-");
        txt7.setText(Integer.toString(NORMAL[0][0]));
        txt8.setText(Integer.toString(NORMAL[0][1]));
        txt9.setText(Integer.toString(NORMAL[0][2]));
        txt10.setText("-");
        txt11.setText("-");
        txt12.setText(Integer.toString(NORMAL[1][0]));
        txt13.setText(Integer.toString(NORMAL[1][1]));
        txt14.setText(Integer.toString(NORMAL[1][2]));
        txt15.setText("-");
        txt16.setText("-");
        txt17.setText(Integer.toString(NORMAL[2][0]));
        txt18.setText(Integer.toString(NORMAL[2][1]));
        txt19.setText(Integer.toString(NORMAL[2][2]));
        txt20.setText("-");
        txt21.setText("-");
        txt22.setText("-");
        txt23.setText("-");
        txt24.setText("-");
        txt25.setText("-");
    }//GEN-LAST:event_radioNormalActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        if(radioBlur.isSelected()){ //montionBlur
            aplicar2(MONTIONBLUR,1.0/9.0,0);//puede ser 1.0/5.0
        }
        if(radioEdge.isSelected()){
            aplicar2(EDGES,1.0/9.0,0.0); //ya esta
        }
        if(radioEmboss.isSelected()){
            aplicar2(EMBOSS,1,128);
        }
        if(radioNormal.isSelected()){
            aplicar(NORMAL,1.0/3.0,0);
        }
        if(radioSharpen.isSelected()){
            aplicar2(SHARPEN,1,0);  
        }
        if(radiob.isSelected()){
            aplicar2(BLUR,1.0/9.0,0);  //ya esta
        }
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void radiobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobActionPerformed
        setLabelsNum(BLUR);
    }//GEN-LAST:event_radiobActionPerformed

    private void setImagenPanel() {
        if (seleccion != null) {
            ImageIcon icon = new ImageIcon(new ImageIcon(seleccion.getPath()).getImage().getScaledInstance(600, 350, Image.SCALE_DEFAULT));
            // this.icono = icon;
            Image image = icon.getImage();
            this.imagen = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_ARGB);
            Graphics2D bGr = imagen.createGraphics();
            bGr.drawImage(image, 0, 0, null);
            bGr.dispose();
            lblImagen.setIcon(icon);
        }
    }

    private void setLabelsNum(int[][] matriz) {
        txt1.setText(Integer.toString(matriz[0][0]));
        txt2.setText(Integer.toString(matriz[0][1]));
        txt3.setText(Integer.toString(matriz[0][2]));
        txt4.setText(Integer.toString(matriz[0][3]));
        txt5.setText(Integer.toString(matriz[0][4]));
        txt6.setText(Integer.toString(matriz[1][0]));
        txt7.setText(Integer.toString(matriz[1][1]));
        txt8.setText(Integer.toString(matriz[1][2]));
        txt9.setText(Integer.toString(matriz[1][3]));
        txt10.setText(Integer.toString(matriz[1][4]));
        txt11.setText(Integer.toString(matriz[2][0]));
        txt12.setText(Integer.toString(matriz[2][1]));
        txt13.setText(Integer.toString(matriz[2][2]));
        txt14.setText(Integer.toString(matriz[2][3]));
        txt15.setText(Integer.toString(matriz[2][4]));
        txt16.setText(Integer.toString(matriz[3][0]));
        txt17.setText(Integer.toString(matriz[3][1]));
        txt18.setText(Integer.toString(matriz[3][2]));
        txt19.setText(Integer.toString(matriz[3][3]));
        txt20.setText(Integer.toString(matriz[3][4]));
        txt21.setText(Integer.toString(matriz[4][0]));
        txt22.setText(Integer.toString(matriz[4][1]));
        txt23.setText(Integer.toString(matriz[4][2]));
        txt24.setText(Integer.toString(matriz[4][3]));
        txt25.setText(Integer.toString(matriz[4][4]));

    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConvolucion().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnOriginal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JRadioButton radioBlur;
    private javax.swing.JRadioButton radioEdge;
    private javax.swing.JRadioButton radioEmboss;
    private javax.swing.JRadioButton radioNormal;
    private javax.swing.JRadioButton radioSharpen;
    private javax.swing.JRadioButton radiob;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt10;
    private javax.swing.JLabel txt11;
    private javax.swing.JLabel txt12;
    private javax.swing.JLabel txt13;
    private javax.swing.JLabel txt14;
    private javax.swing.JLabel txt15;
    private javax.swing.JLabel txt16;
    private javax.swing.JLabel txt17;
    private javax.swing.JLabel txt18;
    private javax.swing.JLabel txt19;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt20;
    private javax.swing.JLabel txt21;
    private javax.swing.JLabel txt22;
    private javax.swing.JLabel txt23;
    private javax.swing.JLabel txt24;
    private javax.swing.JLabel txt25;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txt7;
    private javax.swing.JLabel txt8;
    private javax.swing.JLabel txt9;
    // End of variables declaration//GEN-END:variables
}
